# python3.9のイメージをダウンロード
FROM python:3.9-buster
ENV PYTHONUNBUFFERED=1

WORKDIR /src

# pipを使ってrequiremnts.txtをインストール
ADD requirements.txt .

RUN pip install --trusted-host pypi.python.org -r requirements.txt


COPY api/main.py .

# uvicornのサーバーを立ち上げる
ENTRYPOINT ["poetry", "run", "uvicorn", "api.main:app", "--host", "0.0.0.0", "--reload"]