# python3.9のイメージをダウンロード
FROM python:3.9-buster
ENV PYTHONUNBUFFERED=1

# pipを使ってrequiremnts.txtをインストール
ADD requirements.txt .
RUN pip install --trusted-host pypi.python.org -r requirements.txt

COPY ./api /api

# uvicornのサーバーを立ち上げる

CMD ["uvicorn", "api.main:app", "--reload", "--host=0.0.0.0", "--port=8000"]

EXPOSE 8000